### ISSUE TITLE
I tried to input the data into the training and fit the function. The following problem occurred when printing the function at the end.

### ISSUE THREAD

**Issue by chrisala666** [KindXiaoming/pykan#134]
![image](https://github.com/KindXiaoming/pykan/assets/111328260/31e0fc21-9f25-400d-962d-c99b4685f638)
when i try to fit the function ,this problem occour,
train loss: 7.20e-01 | test loss: 7.39e-01 | reg: 2.51e+01 : 100%|█| 100/100 [00:17<00:00,  5.58it/s
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'extended_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'complex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\py_works\pykan-master\human-temp-fomula-shuffel.py", line 101, in <module>
    model.symbolic_formula()[0][0]
  File "D:\Projects\py_works\pykan-master\kan\KAN.py", line 1239, in symbolic_formula
    self.symbolic_acts = [[ex_round(symbolic_acts[l][i]) for i in range(len(symbolic_acts[l]))] for l in range(len(symbolic_acts))]
  File "D:\Projects\py_works\pykan-master\kan\KAN.py", line 1239, in <listcomp>
    self.symbolic_acts = [[ex_round(symbolic_acts[l][i]) for i in range(len(symbolic_acts[l]))] for l in range(len(symbolic_acts))]
  File "D:\Projects\py_works\pykan-master\kan\KAN.py", line 1239, in <listcomp>
    self.symbolic_acts = [[ex_round(symbolic_acts[l][i]) for i in range(len(symbolic_acts[l]))] for l in range(len(symbolic_acts))]
  File "D:\Projects\py_works\pykan-master\kan\KAN.py", line 1199, in ex_round
    ex2 = ex2.subs(a, round(a, floating_digit))
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\basic.py", line 1088, in fallback
    rv = self.func(*args)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\function.py", line 469, in __new__
    result = super().__new__(cls, *args, **options)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\function.py", line 309, in __new__
    evaluated = cls.eval(*args)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\functions\elementary\hyperbolic.py", line 331, in eval
    i_coeff = _imaginary_unit_as_coefficient(arg)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\functions\elementary\trigonometric.py", line 36, in _imaginary_unit_as_coefficient
    return arg.as_coefficient(S.ImaginaryUnit)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\expr.py", line 1712, in as_coefficient
    r = self.extract_multiplicatively(expr)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\expr.py", line 2245, in extract_multiplicatively
    quotient = self / c
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\decorators.py", line 236, in _func
    return func(self, other)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\decorators.py", line 106, in binary_op_wrapper
    return func(self, other)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\expr.py", line 259, in __truediv__
    return Mul(self, denom)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\operations.py", line 98, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\mul.py", line 285, in flatten
    if not a.is_zero and a.is_Rational:
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 539, in _ask
    fact_i_value = handler_i(obj)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\add.py", line 703, in _eval_is_zero
    if a.is_extended_real:
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 539, in _ask
    fact_i_value = handler_i(obj)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\mul.py", line 1415, in _eval_is_extended_real
    return self._eval_real_imag(True)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\mul.py", line 1422, in _eval_real_imag
    if (t.is_complex or t.is_infinite) is False and t.is_extended_real is False:
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\assumptions.py", line 539, in _ask
    fact_i_value = handler_i(obj)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\functions\elementary\hyperbolic.py", line 474, in _eval_is_positive
    ymod = y % (2*pi)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\decorators.py", line 236, in _func
    return func(self, other)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\decorators.py", line 106, in binary_op_wrapper
    return func(self, other)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\expr.py", line 273, in __mod__
    return Mod(self, other)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\function.py", line 469, in __new__
    result = super().__new__(cls, *args, **options)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\function.py", line 309, in __new__
    evaluated = cls.eval(*args)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\mod.py", line 179, in eval
    a = cls(i, q)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\function.py", line 469, in __new__
    result = super().__new__(cls, *args, **options)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\function.py", line 309, in __new__
    evaluated = cls.eval(*args)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\core\mod.py", line 166, in eval
    G = gcd(p, q)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\polytools.py", line 5393, in gcd
    result = F.gcd(G)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\polytools.py", line 2916, in gcd
    result = F.gcd(G)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\polyclasses.py", line 689, in gcd
    return per(dmp_gcd(F, G, lev, dom))
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\euclidtools.py", line 1625, in dmp_gcd
    return dmp_inner_gcd(f, g, u, K)[0]
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\euclidtools.py", line 1584, in dmp_inner_gcd
    h, cff, cfg = _dmp_inner_gcd(f, g, u, K)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\euclidtools.py", line 1532, in _dmp_inner_gcd
    f = dmp_convert(f, u, K, exact)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\densebasic.py", line 567, in dmp_convert
    return dmp_strip([ dmp_convert(c, v, K0, K1) for c in f ], u)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\densebasic.py", line 567, in <listcomp>
    return dmp_strip([ dmp_convert(c, v, K0, K1) for c in f ], u)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\densebasic.py", line 567, in dmp_convert
    return dmp_strip([ dmp_convert(c, v, K0, K1) for c in f ], u)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\densebasic.py", line 567, in <listcomp>
    return dmp_strip([ dmp_convert(c, v, K0, K1) for c in f ], u)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\densebasic.py", line 561, in dmp_convert
    return dup_convert(f, K0, K1)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\densebasic.py", line 538, in dup_convert
    return dup_strip([ K1.convert(c, K0) for c in f ])
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\densebasic.py", line 538, in <listcomp>
    return dup_strip([ K1.convert(c, K0) for c in f ])
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\domains\domain.py", line 409, in convert
    return self.convert_from(element, base)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\domains\domain.py", line 396, in convert_from
    result = _convert(element, base)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\domains\rationalfield.py", line 136, in from_RealField
    return MPQ(*map(int, K0.to_rational(a)))
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\domains\realfield.py", line 108, in to_rational
    return self._context.to_rational(element, limit)
  File "D:\Anaconda3\envs\py38\lib\site-packages\sympy\polys\domains\mpelements.py", line 142, in to_rational
    k = (ctx.max_denom - q0)//q1
ZeroDivisionError: integer division or modulo by zero

**Comment by chrisala666** [comment]
beg for help /(ㄒoㄒ)/~~

**Comment by JinglaiZheng** [comment]
Try removing the pruning operation **model = model.prune()** and rerunning the code to see if it gives an error.

**Comment by chrisala666** [comment]
> Try removing the pruning operation **model = model.prune()** and rerunning the code to see if it gives an error.

Thx, i tried, but it does't work, still the same erro.

**Comment by yuedajiong** [comment]
try print all parameters, before:
File "D:\Projects\py_works\pykan-master\kan\KAN.py", line 1199, in ex_round
?

**Comment by chrisala666** [comment]
> try print all parameters, before: File "D:\Projects\py_works\pykan-master\kan\KAN.py", line 1199, in ex_round ?

gotcha,  found the problem . When creating model=KAN(), i set too much hidden neurons, now decreasing to 6, works. But haven't found reason leads to this.
