### ISSUE TITLE
Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library

### ISSUE THREAD

**Issue by ash-007-m** [KindXiaoming/pykan#346]
When I am running model.train after model.auto_sysmbolic I am getting this error.

**Comment by KindXiaoming** [comment]
is the loss value nan? Please provide more info about the training.

**Comment by ash-007-m** [comment]
Here is the complete error-
Intel MKL ERROR: Parameter 6 was incorrect on entry to SGELSY.
train loss: nan | test loss: nan | reg: nan :  25%|████▌             | 5/20 [00:25<01:16,  5.13s/it]
Traceback (most recent call last):
  File "hellokan.py", line 53, in <module>
    model.train(dataset, opt="Adam", steps=20, lamb=0.01, lamb_entropy=10.)
  File "/home/ashwini/pykan/kan/MultKAN.py", line 797, in train
    self.update_grid_from_samples(dataset['train_input'][train_id].to(self.device))
  File "/home/ashwini/pykan/kan/MultKAN.py", line 287, in update_grid_from_samples
    self.act_fun[l].update_grid_from_samples(self.acts[l])
  File "/home/ashwini/pykan/kan/KANLayer.py", line 232, in update_grid_from_samples
    self.coef.data = curve2coef(x_pos, y_eval, self.grid, self.k, device=self.device)
  File "/home/ashwini/pykan/kan/spline.py", line 167, in curve2coef
    coef = torch.linalg.lstsq(mat.to(device), y_eval.to(device),
RuntimeError: false INTERNAL ASSERT FAILED at "../aten/src/ATen/native/BatchLinearAlgebra.cpp":1539, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library.

**Comment by edkamesh** [comment]
> is the loss value nan? Please provide more info about the training.

same problem @KindXiaoming the loss value approaches nan, and this error gets thrown, what might be the posssible cause and any fixes to it.

**Comment by KindXiaoming** [comment]
please check if your inputs has a dimension which is always constant (or nearly constant) or a categorical variable.
