### ISSUE TITLE
Any step-by-step guide on KAN with code?

### ISSUE THREAD

**Issue by apavlo89** [KindXiaoming/pykan#376]
Are there any step-by-step guides on how to apply KAN on dataset for dummies (preferably!)?

**Comment by apavlo89** [comment]
I used this guide https://www.kaggle.com/code/seyidcemkarakas/kan-tabular-data-binary-classification for my dataset and got this error:
`checkpoint directory created: ./model
saving model version 0.0
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-16-bff360054870>](https://localhost:8080/#) in <cell line: 41>()
     39 
     40 # KAN model training
---> 41 results = model.train({'train_input': train_input, 'train_label': train_label, 'test_input': val_input, 'test_label': val_label},
     42                       metrics=(train_acc, test_acc),
     43                       opt="LBFGS", steps=100, loss_fn=torch.nn.CrossEntropyLoss()) 

TypeError: Module.train() got an unexpected keyword argument 'metrics'`

`import torch
from kan import KAN

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


# Converting data to Torch tensor
train_input = torch.tensor(X_train.to_numpy(), dtype=torch.float32)
train_label = torch.tensor(y_train.to_numpy(), dtype=torch.long)
val_input = torch.tensor(X_val.to_numpy(), dtype=torch.float32)
val_label = torch.tensor(y_val.to_numpy(), dtype=torch.long)
test_input = torch.tensor(X_test.to_numpy(), dtype=torch.float32)
test_label = torch.tensor(y_test.to_numpy(), dtype=torch.long)
dataset = {
    'train_input': train_input,
    'train_label': train_label,
    'val_input': val_input,
    'val_label': val_label,
    'test_input': test_input,
    'test_label': test_label
}

# Create model
model = KAN(width=[11, 2], grid=10, k=2)

# Fuctions for getting accuracy scores while training
def train_acc():
    preds = torch.argmax(model(dataset['train_input']), dim=1)
    return torch.mean((preds == dataset['train_label']).float())

def test_acc():
    preds = torch.argmax(model(dataset['test_input']), dim=1)
    return torch.mean((preds == dataset['test_label']).float())

# KAN model training
results = model.train({'train_input': train_input, 'train_label': train_label, 'test_input': val_input, 'test_label': val_label},
                      metrics=(train_acc, test_acc),
                      opt="LBFGS", steps=100, loss_fn=torch.nn.CrossEntropyLoss()) 


# Predictions of train val and test datasets
test_preds = torch.argmax(model.forward(test_input).detach(),dim=1)
test_labels = test_label

train_preds = torch.argmax(model.forward(train_input).detach(),dim=1)
train_labels = train_label

val_preds = torch.argmax(model.forward(val_input).detach(),dim=1)
val_labels = val_label


# Evaluate metrics

print("Train ACC:", accuracy_score(train_labels.numpy(), train_preds.numpy()))

print("Val ACC:", accuracy_score(val_labels.numpy(), val_preds.numpy()))

print("Test ACC:", accuracy_score(test_labels.numpy(), test_preds.numpy()))


# Plotting KAN network
model.plot(scale=10)

# Learning curve based on ACC and LOSS
plt.figure(figsize=(10, 5))
plt.plot(results["train_acc"], label='Training Accuracy')
plt.plot(results["test_acc"], label='Val Accuracy')
plt.plot(results["train_loss"], label='Training Loss')
plt.plot(results["test_loss"], label='Val Loss')
plt.title('Training and Val Accuracy over Iterations')
plt.xlabel('Iteration')
plt.ylabel('Accuracy & Loss')
plt.legend()
plt.grid(True)
plt.show()`

**Comment by seyidcemkarakas** [comment]
Hi @apavlo89 

I saw your comments on Kaggle on my notebook. Firstly thanks for looking.

Seconly, I run my code again but I dont get any errors. Can you share verisons of your libraries ?

**Comment by zozi0406** [comment]
Hi, I'm getting the exact same issue on version 0.2.3 - seems like train is not defined in KAN anymore. Instead, there is now the fit method. However, there I'm getting different errors...

  File "c:\[redacted]\main.py", line 44, in <module>
    results = model.fit(
  File "C:\[redacted]\lib\site-packages\kan\MultKAN.py", line 946, in fit
    self.update_grid(dataset['train_input'][train_id])
  File "C:\[redacted]\lib\site-packages\kan\MultKAN.py", line 358, in update_grid
    self.update_grid_from_samples(x)
  File "C:\[redacted]\lib\site-packages\kan\MultKAN.py", line 354, in update_grid_from_samples
    self.get_act(x)
  File "C:\[redacted]\lib\site-packages\kan\MultKAN.py", line 1739, in get_act
    self.forward(x)
  File "C:\[redacted]\lib\site-packages\kan\MultKAN.py", line 389, in forward
    x_numerical, preacts, postacts_numerical, postspline = self.act_fun[l](x)
  File "C:\[redacted]\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\[redacted]\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\[redacted]\lib\site-packages\kan\KANLayer.py", line 183, in forward
    y = coef2curve(x_eval=x, grid=self.grid, coef=self.coef, k=self.k)  # y shape: (batch, in_dim, out_dim)
  File "C:\[redacted]\lib\site-packages\kan\spline.py", line 118, in coef2curve
    y_eval = torch.einsum('ijk,jlk->ijl', b_splines, coef.to(b_splines.device))
  File "C:\[redacted]\lib\site-packages\torch\functional.py", line 380, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: expected scalar type Float but found Double

**Comment by zozi0406** [comment]
Since 0.2.0, you will need to use the fit method instead of train.

**Comment by seyidcemkarakas** [comment]
> Hi @apavlo89,
> 
> Since 0.2.0, you will need to use the fit method instead of train.

Yes, @apavlo89 Could you try it?

**Comment by apavlo89** [comment]
different error now:

```
import torch
from kan import KAN

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


# Converting data to Torch tensor
train_input = torch.tensor(X_train.to_numpy(), dtype=torch.float32)
train_label = torch.tensor(y_train.to_numpy(), dtype=torch.long)
val_input = torch.tensor(X_val.to_numpy(), dtype=torch.float32)
val_label = torch.tensor(y_val.to_numpy(), dtype=torch.long)
test_input = torch.tensor(X_test.to_numpy(), dtype=torch.float32)
test_label = torch.tensor(y_test.to_numpy(), dtype=torch.long)
dataset = {
    'train_input': train_input,
    'train_label': train_label,
    'val_input': val_input,
    'val_label': val_label,
    'test_input': test_input,
    'test_label': test_label
}

# Create model
model = KAN(width=[11, 2], grid=10, k=2)

# Fuctions for getting accuracy scores while training
def train_acc():
    preds = torch.argmax(model(dataset['train_input']), dim=1)
    return torch.mean((preds == dataset['train_label']).float())

def test_acc():
    preds = torch.argmax(model(dataset['test_input']), dim=1)
    return torch.mean((preds == dataset['test_label']).float())

# KAN model training
results = model.fit({'train_input': train_input, 'train_label': train_label, 'test_input': val_input, 'test_label': val_label},
                      metrics=(train_acc, test_acc),
                      opt="LBFGS", steps=100, loss_fn=torch.nn.CrossEntropyLoss()) 


# Predictions of train val and test datasets
test_preds = torch.argmax(model.forward(test_input).detach(),dim=1)
test_labels = test_label

train_preds = torch.argmax(model.forward(train_input).detach(),dim=1)
train_labels = train_label

val_preds = torch.argmax(model.forward(val_input).detach(),dim=1)
val_labels = val_label


# Evaluate metrics

print("Train ACC:", accuracy_score(train_labels.numpy(), train_preds.numpy()))

print("Val ACC:", accuracy_score(val_labels.numpy(), val_preds.numpy()))

print("Test ACC:", accuracy_score(test_labels.numpy(), test_preds.numpy()))


# Plotting KAN network
model.plot(scale=10)

# Learning curve based on ACC and LOSS
plt.figure(figsize=(10, 5))
plt.plot(results["train_acc"], label='Training Accuracy')
plt.plot(results["test_acc"], label='Val Accuracy')
plt.plot(results["train_loss"], label='Training Loss')
plt.plot(results["test_loss"], label='Val Loss')
plt.title('Training and Val Accuracy over Iterations')
plt.xlabel('Iteration')
plt.ylabel('Accuracy & Loss')
plt.legend()
plt.grid(True)
plt.show()
```

`checkpoint directory created: ./model
saving model version 0.0

description:   0%|                                                          | 0/100 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-14-e3e291a4e23a>](https://localhost:8080/#) in <cell line: 41>()
     39 
     40 # KAN model training
---> 41 results = model.fit({'train_input': train_input, 'train_label': train_label, 'test_input': val_input, 'test_label': val_label},
     42                       metrics=(train_acc, test_acc),
     43                       opt="LBFGS", steps=100, loss_fn=torch.nn.CrossEntropyLoss()) 

4 frames
[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in fit(self, dataset, opt, steps, log, lamb, lamb_l1, lamb_entropy, lamb_coef, lamb_coefdiff, update_grid, grid_update_num, loss_fn, lr, start_grid_update_step, stop_grid_update_step, batch, metrics, save_fig, in_vars, out_vars, beta, save_fig_freq, img_folder, singularity_avoiding, y_th, reg_metric, display_metrics)
    944 
    945             if _ % grid_update_freq == 0 and _ < stop_grid_update_step and update_grid and _ >= start_grid_update_step:
--> 946                 self.update_grid(dataset['train_input'][train_id])
    947 
    948             if opt == "LBFGS":

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in update_grid(self, x)
    356 
    357     def update_grid(self, x):
--> 358         self.update_grid_from_samples(x)
    359 
    360     def initialize_grid_from_another_model(self, model, x):

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in update_grid_from_samples(self, x)
    352     def update_grid_from_samples(self, x):
    353         for l in range(self.depth):
--> 354             self.get_act(x)
    355             self.act_fun[l].update_grid_from_samples(self.acts[l])
    356 

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in get_act(self, x)
   1737         save_act = self.save_act
   1738         self.save_act = True
-> 1739         self.forward(x)
   1740         self.save_act = save_act
   1741 

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in forward(self, x, singularity_avoiding, y_th)
    365     def forward(self, x, singularity_avoiding=False, y_th=10.):
    366 
--> 367         assert x.shape[1] == self.width_in[0]
    368 
    369         x = x[:,self.input_id.long()]

AssertionError:`

**Comment by apavlo89** [comment]
Also how would one go about doing feature selection with KAN?

**Comment by seyidcemkarakas** [comment]
> Also how would one go about doing feature selection with KAN?

I have wrote code for feature selection, I will share it

**Comment by apavlo89** [comment]
Exciting! Where will you post it?

**Comment by KindXiaoming** [comment]
an example of how to do feature selection using KANs: https://github.com/KindXiaoming/pykan/blob/master/tutorials/Interp_4_feature_attribution.ipynb

**Comment by apavlo89** [comment]
It just doesn't like my dataset for some reason I've tried all kinds of things but i get these error - any idea why?:

```
from kan import *
import numpy as np

# Assuming X_train, y_train, X_val, y_val, X_test, y_test are already defined

# Combine training and validation sets
X_train_combined = np.concatenate((X_train, X_val), axis=0)
y_train_combined = np.concatenate((y_train, y_val), axis=0)

# Ensure no None values and correct shapes
assert X_train_combined is not None
assert y_train_combined is not None
assert X_test is not None
assert y_test is not None
assert X_train_combined.shape[0] == y_train_combined.shape[0]
assert X_test.shape[0] == y_test.shape[0]

# Convert y_train_combined and y_test to float, as sometimes integer arrays might cause issues
y_train_combined = y_train_combined.astype(float)
y_test = y_test.astype(float)

# Debugging: Print shapes and types of the dataset elements
print(f"train_input shape: {X_train_combined.shape}, dtype: {X_train_combined.dtype}")
print(f"train_output shape: {y_train_combined.shape}, dtype: {y_train_combined.dtype}")
print(f"test_input shape: {X_test.shape}, dtype: {X_test.dtype}")
print(f"test_output shape: {y_test.shape}, dtype: {y_test.dtype}")

# Create the dataset in the expected format
dataset = {
    'train_input': X_train_combined,
    'train_output': y_train_combined,
    'test_input': X_test,
    'test_output': y_test
}

# Verify the dataset structure
print(f"dataset keys: {dataset.keys()}")
for key in dataset:
    print(f"{key} shape: {dataset[key].shape}, dtype: {dataset[key].dtype}")

# Function to safely check if an array is None or empty
def safe_check_none(arr):
    return arr is None or (isinstance(arr, np.ndarray) and arr.size == 0)

# Check for None values explicitly before passing to model
if safe_check_none(dataset['train_input']) or safe_check_none(dataset['train_output']) or safe_check_none(dataset['test_input']) or safe_check_none(dataset['test_output']):
    raise ValueError("One of the dataset components is None or empty")

# Create and train the KAN model
model = KAN(width=[X_train_combined.shape[1], 10, 10, 1], seed=2)

# Explicitly define a function to handle the ambiguous truth value check
def custom_fit(model, dataset, *args, **kwargs):
    try:
        model.fit(dataset, *args, **kwargs)
    except ValueError as e:
        if "ambiguous truth value" in str(e):
            print("Handling ambiguous truth value check")
            model.fit(dataset, *args, **kwargs)
        else:
            raise e

# Use the custom fit function
custom_fit(model, dataset, steps=50, lamb=1e-3, reg_metric='edge_forward_n')

```

```

train_input shape: (2134, 3854), dtype: float64
train_output shape: (2134,), dtype: float64
test_input shape: (251, 3854), dtype: float64
test_output shape: (251,), dtype: float64
dataset keys: dict_keys(['train_input', 'train_output', 'test_input', 'test_output'])
train_input shape: (2134, 3854), dtype: float64
train_output shape: (2134,), dtype: float64
test_input shape: (251, 3854), dtype: float64
test_output shape: (251,), dtype: float64
checkpoint directory created: ./model
saving model version 0.0

description:   0%|                                                           | 0/50 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-36-8c207fd00f61>](https://localhost:8080/#) in <cell line: 64>()
     62 
     63 # Use the custom fit function
---> 64 custom_fit(model, dataset, steps=50, lamb=1e-3, reg_metric='edge_forward_n')

5 frames
[<ipython-input-36-8c207fd00f61>](https://localhost:8080/#) in custom_fit(model, dataset, *args, **kwargs)
     59             model.fit(dataset, *args, **kwargs)
     60         else:
---> 61             raise e
     62 
     63 # Use the custom fit function

[<ipython-input-36-8c207fd00f61>](https://localhost:8080/#) in custom_fit(model, dataset, *args, **kwargs)
     53 def custom_fit(model, dataset, *args, **kwargs):
     54     try:
---> 55         model.fit(dataset, *args, **kwargs)
     56     except ValueError as e:
     57         if "ambiguous truth value" in str(e):

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in fit(self, dataset, opt, steps, log, lamb, lamb_l1, lamb_entropy, lamb_coef, lamb_coefdiff, update_grid, grid_update_num, loss_fn, lr, start_grid_update_step, stop_grid_update_step, batch, metrics, save_fig, in_vars, out_vars, beta, save_fig_freq, img_folder, singularity_avoiding, y_th, reg_metric, display_metrics)
    944 
    945             if _ % grid_update_freq == 0 and _ < stop_grid_update_step and update_grid and _ >= start_grid_update_step:
--> 946                 self.update_grid(dataset['train_input'][train_id])
    947 
    948             if opt == "LBFGS":

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in update_grid(self, x)
    356 
    357     def update_grid(self, x):
--> 358         self.update_grid_from_samples(x)
    359 
    360     def initialize_grid_from_another_model(self, model, x):

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in update_grid_from_samples(self, x)
    352     def update_grid_from_samples(self, x):
    353         for l in range(self.depth):
--> 354             self.get_act(x)
    355             self.act_fun[l].update_grid_from_samples(self.acts[l])
    356 

[/usr/local/lib/python3.10/dist-packages/kan/MultKAN.py](https://localhost:8080/#) in get_act(self, x)
   1730         if isinstance(x, dict):
   1731             x = x['train_input']
-> 1732         if x == None:
   1733             if self.cache_data != None:
   1734                 x = self.cache_data

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by seyidcemkarakas** [comment]
@apavlo89  Here is my code for feature importance:

```python
# Modeli oluşturma
model = KAN(width=[4,7,1], grid=3, k=11)

# Modeli eğitme
results = model.train({'train_input': train_input, 'train_label': train_label, 'test_input': val_input, 'test_label': val_label},
                      opt="LBFGS", steps=150, loss_fn=torch.nn.MSELoss())

# Validaionları verdik her ne kadar 'test_input': val_input yazsa da çünkü KAN model train dataset dict'ında test_input adlı bir dict istiyo


layer_1 = model.acts_scale[0].detach().numpy()
layer_2 = model.acts_scale[1].detach().numpy()


columns = list(X.columns)
importance_values = np.dot(layer_1.T, layer_2.T).flatten()

sorted_indices = np.argsort(importance_values)[::1]
sorted_importance_values = importance_values[sorted_indices]
sorted_columns = np.array(columns)[sorted_indices]



# Bar plot oluşturma
plt.figure(figsize=(12, 6))
plt.barh(sorted_columns, sorted_importance_values, color='skyblue')
plt.xlabel('Feature Importance')
plt.ylabel('Features')
plt.title('Feature Importance of KAN')
plt.show()
```

You will see the barh plot

**Comment by KindXiaoming** [comment]
Hi @apavlo89 , looks like your data are numpy array, could you please try convert them to torch tensors?

**Comment by apavlo89** [comment]
```
import torch
from kan import KAN

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Check the shape of your data
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_val: {X_val.shape}")
print(f"Shape of X_test: {X_test.shape}")

# Converting data to NumPy arrays
X_train_np = X_train.to_numpy()
y_train_np = y_train.to_numpy()
X_val_np = X_val.to_numpy()
y_val_np = y_val.to_numpy()
X_test_np = X_test.to_numpy()
y_test_np = y_test.to_numpy()

# Converting data to Torch tensor
train_input = torch.tensor(X_train_np, dtype=torch.float32)
train_label = torch.tensor(y_train_np, dtype=torch.long)
val_input = torch.tensor(X_val_np, dtype=torch.float32)
val_label = torch.tensor(y_val_np, dtype=torch.long)
test_input = torch.tensor(X_test_np, dtype=torch.float32)
test_label = torch.tensor(y_test_np, dtype=torch.long)

dataset = {
    'train_input': train_input,
    'train_label': train_label,
    'val_input': val_input,
    'val_label': val_label,
    'test_input': test_input,
    'test_label': test_label
}

# Ensure the input width matches the number of features
input_width = X_train_np.shape[1]

# Create model
model = KAN(width=[input_width, 2], grid=10, k=2)

# Workaround for the issue by setting save_act to False
model.save_act = False

# Functions for getting accuracy scores while training
def train_acc():
    preds = torch.argmax(model(dataset['train_input']), dim=1)
    return torch.mean((preds == dataset['train_label']).float())

def test_acc():
    preds = torch.argmax(model(dataset['test_input']), dim=1)
    return torch.mean((preds == dataset['test_label']).float())

# KAN model training using the fit method
results = model.fit({'train_input': train_input, 'train_label': train_label, 'test_input': val_input, 'test_label': val_label},
                    opt="LBFGS", steps=150, loss_fn=torch.nn.CrossEntropyLoss())

layer_1 = model.acts_scale[0].detach().numpy()
layer_2 = model.acts_scale[1].detach().numpy()

columns = list(X_train.columns)
importance_values = np.dot(layer_1.T, layer_2.T).flatten()

sorted_indices = np.argsort(importance_values)[::1]
sorted_importance_values = importance_values[sorted_indices]
sorted_columns = np.array(columns)[sorted_indices]

# Create the bar plot
plt.figure(figsize=(12, 6))
plt.barh(sorted_columns, sorted_importance_values, color='skyblue')
plt.xlabel('Feature Importance')
plt.ylabel('Features')
plt.title('Feature Importance of KAN')
plt.show()
```

Output and error :/ Dreaming of the day someone makes an easy to use autoKAN package.. W
```

Shape of X_train: (1886, 171)
Shape of X_val: (251, 171)
Shape of X_test: (253, 171)
checkpoint directory created: ./model
saving model version 0.0
| train_loss: nan | test_loss: nan | reg: 0.00e+00 | : 100%|██████| 150/150 [01:42<00:00,  1.46it/s]saving model version 0.1

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-12-674e38bca30b>](https://localhost:8080/#) in <cell line: 63>()
     61                     opt="LBFGS", steps=150, loss_fn=torch.nn.CrossEntropyLoss())
     62 
---> 63 layer_1 = model.acts_scale[0].detach().numpy()
     64 layer_2 = model.acts_scale[1].detach().numpy()
     65 

IndexError: list index out of range
```

**Comment by KindXiaoming** [comment]
try print(model.acts_scale), is it None? If yes, what is model.save_act (True or False)? If you try a dataset which does not return nan loss, does this problem persist?

**Comment by apavlo89** [comment]
If i remove the feature selection code then it runs just fine. the issue appears in the feature selection part:

```

import torch
from kan import KAN

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Check the shape of your data
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_val: {X_val.shape}")
print(f"Shape of X_test: {X_test.shape}")

# Converting data to NumPy arrays
X_train_np = X_train.to_numpy()
y_train_np = y_train.to_numpy()
X_val_np = X_val.to_numpy()
y_val_np = y_val.to_numpy()
X_test_np = X_test.to_numpy()
y_test_np = y_test.to_numpy()

# Converting data to Torch tensor
train_input = torch.tensor(X_train_np, dtype=torch.float32)
train_label = torch.tensor(y_train_np, dtype=torch.long)
val_input = torch.tensor(X_val_np, dtype=torch.float32)
val_label = torch.tensor(y_val_np, dtype=torch.long)
test_input = torch.tensor(X_test_np, dtype=torch.float32)
test_label = torch.tensor(y_test_np, dtype=torch.long)

dataset = {
    'train_input': train_input,
    'train_label': train_label,
    'val_input': val_input,
    'val_label': val_label,
    'test_input': test_input,
    'test_label': test_label
}

# Ensure the input width matches the number of features
input_width = X_train_np.shape[1]

# Create model
model = KAN(width=[input_width, 2], grid=4, k=1)

# Workaround for the issue by setting save_act to False
model.save_act = False

# Functions for getting accuracy scores while training
def train_acc():
    preds = torch.argmax(model(dataset['train_input']), dim=1)
    return torch.mean((preds == dataset['train_label']).float())

def test_acc():
    preds = torch.argmax(model(dataset['test_input']), dim=1)
    return torch.mean((preds == dataset['test_label']).float())

# KAN model training using the fit method
results = model.fit({'train_input': train_input, 'train_label': train_label, 'test_input': val_input, 'test_label': val_label},
                    opt="LBFGS", steps=100, loss_fn=torch.nn.CrossEntropyLoss())
#opt can be Adam or LBFGS
print(model.acts_scale)
#####################################feature selection###########################################
layer_1 = model.acts_scale[0].detach().numpy()
layer_2 = model.acts_scale[1].detach().numpy()

columns = list(X_train.columns)
importance_values = np.dot(layer_1.T, layer_2.T).flatten()

sorted_indices = np.argsort(importance_values)[::1]
sorted_importance_values = importance_values[sorted_indices]
sorted_columns = np.array(columns)[sorted_indices]

## Create the bar plot
plt.figure(figsize=(12, 6))
plt.barh(sorted_columns, sorted_importance_values, color='skyblue')
plt.xlabel('Feature Importance')
plt.ylabel('Features')
plt.title('Feature Importance of KAN')
plt.show()
##################################################################################################

# Predictions of train val and test datasets
test_preds = torch.argmax(model.forward(test_input).detach(),dim=1)
test_labels = test_label

train_preds = torch.argmax(model.forward(train_input).detach(),dim=1)
train_labels = train_label

val_preds = torch.argmax(model.forward(val_input).detach(),dim=1)
val_labels = val_label


# Evaluate metrics

print("Train ACC:", accuracy_score(train_labels.numpy(), train_preds.numpy()))

print("Val ACC:", accuracy_score(val_labels.numpy(), val_preds.numpy()))

print("Test ACC:", accuracy_score(test_labels.numpy(), test_preds.numpy()))

# Plotting KAN network
#model.plot(scale=input_width)
print(results)

# Learning curve based on ACC and LOSS
plt.figure(figsize=(10, 5))
plt.plot(results["train_acc"], label='Training Accuracy')
plt.plot(results["test_acc"], label='Val Accuracy')
plt.plot(results["train_loss"], label='Training Loss')
plt.plot(results["test_loss"], label='Val Loss')
plt.title('Training and Val Accuracy over Iterations')
plt.xlabel('Iteration')
plt.ylabel('Accuracy & Loss')
plt.legend()
plt.grid(True)
plt.show()
```

`Shape of X_train: (1886, 171)
Shape of X_val: (251, 171)
Shape of X_test: (253, 171)
checkpoint directory created: ./model
saving model version 0.0
| train_loss: 6.57e-01 | test_loss: 9.09e-01 | reg: 0.00e+00 | : 100%|█| 100/100 [01:40<00:00,  1.01saving model version 0.1
[]

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-15-2fd2aad7cec2>](https://localhost:8080/#) in <cell line: 65>()
     63 print(model.acts_scale)
     64 #####################################feature selection###########################################
---> 65 layer_1 = model.acts_scale[0].detach().numpy()
     66 layer_2 = model.acts_scale[1].detach().numpy()
     67 

IndexError: list index out of range`
